### PR TITLE
Added starting folders and files.

### PR DESCRIPTION
**Pull request by jkaganovsky**
Added starting folders and files

### CODE REVIEW

**Comment by bfourGitHub** [comment]
Initial Commit Review

**Review by bfourGitHub — DISMISSED** [review]
Comment Comment

**Review by mfrisch87 — DISMISSED** [review]

**Review by bfourGitHub — DISMISSED** [review]
Just a quick review!

**Review by bfourGitHub — APPROVED** [review]
I've reviewed, 2 checks have passed.

**Pull request merged**
